# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    groups:
      babel:
        patterns:
          - '@babel/*'
          - 'babel*'
      docusaurus:
        patterns:
          - '@docusaurus/*'
      react:
        patterns:
          - 'react'
          - 'react-*'

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
