allowBuilds:
  '@swc/core': true
  core-js: false
  core-js-pure: false
  esbuild: false

linkWorkspacePackages: true
hoistPattern:
  - '*'
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
strictPeerDependencies: false
autoInstallPeers: true
savePrefix: ''
dedupePeerDependents: true
